
(function(){
const KEY='loadstudio_complete_state_v1';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(window.LOAD_STUDIO_INITIAL);
let featureData=window.LOAD_STUDIO_FEATURES;
let currentScene=0;
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(state));render();}
function uid(prefix){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,5)}
function log(msg){state.logs=state.logs||[];state.logs.push(new Date().toLocaleTimeString()+' - '+msg);localStorage.setItem(KEY,JSON.stringify(state));}
function modal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.add('show')}
function closeModal(){$('#modal').classList.remove('show')}
function download(name,text,type='application/json'){const b=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function go(id){$$('.section').forEach(s=>s.classList.remove('active')); const el=$('#section-'+id); if(el){el.classList.add('active'); el.scrollIntoView({behavior:'smooth',block:'start'});} }
function sectionById(id){return featureData.sections.find(s=>s.id===id)}
function statusText(section){if(section.type==='integration')return 'Integration Required: this tool needs API keys, backend, microphone permission, FFmpeg, cloud storage, Load Play endpoint, or live provider access.'; if(section.type==='mixed')return 'Local workflow is implemented. Live provider or backend actions are marked Integration Required where needed.'; return 'Local workflow implemented in this PWA.'}
function controlsFor(sec){
 const id=sec.id;
 let common=`<div class="actions"><button class="btn primary" data-action="add-item" data-section-id="${id}">Add ${esc(sec.title)} Item</button><button class="btn secondary" data-action="export-section" data-section-id="${id}">Export Section JSON</button><button class="btn secondary" data-action="open-integration" data-section-id="${id}">Integration Notes</button></div><p class="lead" style="margin-top:10px">${statusText(sec)}</p>`;
 if(id==='projects'||id==='dashboard') return `<div class="form-grid"><div class="field"><label>Project title</label><input id="projectTitle" value="Untitled Load Studio Project"></div><div class="field"><label>Type</label><select id="projectType"><option>Feature Film</option><option>Short Film</option><option>Episodic Series</option><option>Documentary</option><option>Digital Book Cinema</option><option>CinePWA Project</option></select></div><div class="field"><label>Status</label><select id="projectStatus"><option>draft</option><option>editing</option><option>ready</option><option>exported</option><option>published</option></select></div><div class="field"><label>Folder</label><input id="projectFolder" value="Studio Projects"></div><div class="field" style="grid-column:1/-1"><label>Description</label><textarea id="projectDescription">Production notes, rights summary and Load Play preparation.</textarea></div></div>${common}`;
 if(id==='scene-builder') return `<div class="form-grid"><div class="field"><label>Scene title</label><input id="sceneTitle" value="New Scene"></div><div class="field"><label>Chapter</label><input id="sceneChapter" value="Chapter 1"></div><div class="field"><label>Characters</label><input id="sceneCharacters" value="Narrator"></div><div class="field"><label>Location</label><input id="sceneLocation" value="Studio stage"></div><div class="field"><label>Mood</label><input id="sceneMood" value="cinematic"></div><div class="field"><label>Duration</label><input id="sceneDuration" type="number" value="8"></div><div class="field"><label>Status</label><select id="sceneStatus"><option>draft</option><option>needs image</option><option>needs voice</option><option>needs music</option><option>needs review</option><option>locked</option><option>exported</option></select></div><div class="field"><label>Transition</label><input id="sceneTransition" value="fade"></div><div class="field" style="grid-column:1/-1"><label>Narration</label><textarea id="sceneNarration">Scene narration.</textarea></div><div class="field" style="grid-column:1/-1"><label>Image Prompt</label><textarea id="scenePrompt">cinematic scene image prompt</textarea></div></div><div class="actions"><button class="btn primary" data-action="add-scene">Add Scene Card</button><button class="btn secondary" data-action="play-preview">Preview</button><button class="btn secondary" data-action="export-scenes">Export Scenes</button></div>`;
 if(id==='vn-tools'||id==='timeline-editor') return `<div class="ls-vn-editor"><style>
.ls-vn-editor{display:flex;flex-direction:column;gap:0;background:#0c0518;border:1px solid rgba(125,42,232,.32);border-radius:12px;overflow:hidden;color:#f5f0ff;font-family:Inter,-apple-system,system-ui,sans-serif}
.ls-vn-toolbar{display:flex;flex-wrap:nowrap;overflow-x:auto;align-items:center;gap:6px;padding:8px 10px;background:rgba(22,11,38,.96);border-bottom:1px solid rgba(125,42,232,.22);scrollbar-width:none}
.ls-vn-toolbar::-webkit-scrollbar{display:none}
.ls-vn-tool{display:inline-flex;align-items:center;justify-content:center;width:32px;height:32px;border-radius:7px;background:rgba(125,42,232,.14);border:1px solid rgba(125,42,232,.28);color:#e0d8f5;cursor:pointer;flex-shrink:0;font-family:inherit}
.ls-vn-tool:hover{background:rgba(125,42,232,.28);color:#fff}
.ls-vn-tool svg{width:16px;height:16px}
.ls-vn-tool.primary{background:rgba(125,42,232,.32);border-color:rgba(179,58,240,.55);color:#fff}
.ls-vn-tool-sep{width:1px;height:22px;background:rgba(125,42,232,.32);margin:0 4px;flex-shrink:0}
.ls-vn-stage{flex:0 0 auto;min-height:560px;background:#000;display:flex;align-items:center;justify-content:center;position:relative;border-bottom:1px solid rgba(125,42,232,.18)}
@media(max-width:760px){.ls-vn-stage{min-height:420px}}
.ls-vn-stage-art{position:absolute;inset:0;background:radial-gradient(ellipse at 50% 40%,rgba(125,42,232,.35) 0%,rgba(125,42,232,.08) 35%,#000 70%);display:flex;align-items:center;justify-content:center;text-align:center;color:#a78bfa}
.ls-vn-stage-art .play-ring{width:96px;height:96px;border-radius:50%;border:3px solid rgba(179,58,240,.6);display:flex;align-items:center;justify-content:center;background:rgba(125,42,232,.18);box-shadow:0 0 60px rgba(125,42,232,.45)}
.ls-vn-stage-art .play-ring svg{width:42px;height:42px;color:#fff}
.ls-vn-stage-meta{position:absolute;left:14px;bottom:14px;background:rgba(8,4,18,.6);padding:6px 10px;border-radius:6px;font-size:12px;color:#e0d8f5;backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px)}
.ls-vn-controls{display:flex;align-items:center;gap:10px;padding:10px 14px;background:rgba(16,7,31,.94);border-bottom:1px solid rgba(125,42,232,.22)}
.ls-vn-pcb{display:inline-flex;align-items:center;justify-content:center;width:34px;height:34px;border-radius:50%;background:rgba(125,42,232,.18);border:1px solid rgba(125,42,232,.32);color:#e0d8f5;cursor:pointer;flex-shrink:0}
.ls-vn-pcb.play{width:42px;height:42px;background:linear-gradient(135deg,#7d2ae8,#b33af0);border:0;color:#fff;box-shadow:0 4px 16px rgba(125,42,232,.5)}
.ls-vn-pcb svg{width:16px;height:16px}
.ls-vn-pcb.play svg{width:20px;height:20px}
.ls-vn-time{font-variant-numeric:tabular-nums;color:#c0b8d9;font-size:12.5px;flex-shrink:0;min-width:84px;text-align:center}
.ls-vn-seek{flex:1;height:6px;border-radius:3px;background:rgba(125,42,232,.18);position:relative;overflow:hidden;cursor:pointer}
.ls-vn-seek-fill{position:absolute;left:0;top:0;bottom:0;width:38%;background:linear-gradient(90deg,#b33af0,#7d2ae8);border-radius:3px}
.ls-vn-seek-thumb{position:absolute;left:38%;top:50%;width:14px;height:14px;border-radius:50%;background:#fff;transform:translate(-50%,-50%);box-shadow:0 0 0 4px rgba(125,42,232,.35)}
.ls-vn-vol{display:inline-flex;align-items:center;gap:6px;flex-shrink:0}
.ls-vn-vol input[type=range]{width:80px;accent-color:#b33af0}
.ls-vn-timeline{background:#0a0414;padding:10px 14px 14px;display:grid;grid-template-columns:96px 1fr;gap:0;align-items:stretch;height:280px;overflow:hidden;border-top:1px solid rgba(125,42,232,.22)}
.ls-vn-tracks-labels{display:flex;flex-direction:column;gap:6px;padding-top:24px;border-right:1px solid rgba(125,42,232,.22);padding-right:8px}
.ls-vn-track-label{height:48px;display:flex;align-items:center;color:#c0b8d9;font-size:11.5px;font-weight:700;letter-spacing:.04em;text-transform:uppercase;flex-shrink:0}
.ls-vn-tracks-scroll{position:relative;overflow-x:auto;overflow-y:hidden;padding-top:24px;-webkit-overflow-scrolling:touch}
.ls-vn-tracks-scroll::-webkit-scrollbar{height:6px}
.ls-vn-tracks-scroll::-webkit-scrollbar-thumb{background:rgba(125,42,232,.4);border-radius:3px}
.ls-vn-ruler{position:absolute;top:0;left:0;right:0;height:18px;display:flex;align-items:center;padding-left:0;font-size:10px;color:rgba(192,184,217,.6);font-variant-numeric:tabular-nums;border-bottom:1px solid rgba(125,42,232,.18)}
.ls-vn-ruler span{flex:0 0 80px;text-align:left;padding-left:4px}
.ls-vn-track-row{height:48px;display:flex;align-items:center;gap:6px;margin-bottom:6px;min-width:max-content}
.ls-vn-clip{height:40px;border-radius:6px;display:flex;align-items:center;justify-content:center;font-size:11.5px;font-weight:600;color:#fff;cursor:pointer;flex-shrink:0;border:1px solid rgba(125,42,232,.5);box-shadow:inset 0 1px 0 rgba(255,255,255,.06)}
.ls-vn-clip.selected{border:2px solid #7d2ae8;box-shadow:0 0 0 2px rgba(125,42,232,.35),inset 0 1px 0 rgba(255,255,255,.08)}
.ls-vn-clip.media{background:linear-gradient(135deg,#3a0e5e,#5a1a8c)}
.ls-vn-clip.voice{background:linear-gradient(135deg,#0e3a5e,#1a5a8c)}
.ls-vn-clip.music{background:linear-gradient(135deg,#5e0e3a,#8c1a5a)}
.ls-vn-clip.sfx{background:linear-gradient(135deg,#5e3a0e,#8c5a1a)}
.ls-vn-clip.subtitle{background:linear-gradient(135deg,#0e5e3a,#1a8c5a)}
.ls-vn-actions{display:flex;justify-content:flex-end;gap:8px;padding:10px 14px;background:rgba(8,4,18,.7);border-top:1px solid rgba(125,42,232,.22)}
.ls-vn-actions .btn{padding:7px 14px;border-radius:8px;background:rgba(125,42,232,.22);border:1px solid rgba(125,42,232,.4);color:#fff;font-weight:700;font-size:12.5px;cursor:pointer;font-family:inherit}
.ls-vn-actions .btn.primary{background:linear-gradient(135deg,#7d2ae8,#b33af0);border:0;box-shadow:0 4px 14px rgba(125,42,232,.45)}
</style>
<div class="ls-vn-toolbar" role="toolbar" aria-label="Editor tools">
<button class="ls-vn-tool" type="button" aria-label="Undo" title="Undo"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 14 4 9 9 4"/><path d="M20 20v-7a4 4 0 0 0-4-4H4"/></svg></button>
<button class="ls-vn-tool" type="button" aria-label="Redo" title="Redo"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="15 14 20 9 15 4"/><path d="M4 20v-7a4 4 0 0 1 4-4h12"/></svg></button>
<span class="ls-vn-tool-sep"></span>
<button class="ls-vn-tool primary" type="button" aria-label="Save" title="Save"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"/><polyline points="17 21 17 13 7 13 7 21"/><polyline points="7 3 7 8 15 8"/></svg></button>
<button class="ls-vn-tool" type="button" aria-label="Add scene" title="Add scene"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg></button>
<button class="ls-vn-tool" type="button" aria-label="Cut" title="Cut"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="6" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><line x1="20" y1="4" x2="8.12" y2="15.88"/><line x1="14.47" y1="14.48" x2="20" y2="20"/><line x1="8.12" y1="8.12" x2="12" y2="12"/></svg></button>
<button class="ls-vn-tool" type="button" aria-label="Link clips" title="Link clips"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></svg></button>
<span class="ls-vn-tool-sep"></span>
<button class="ls-vn-tool" type="button" aria-label="Add image" title="Add image"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="9" cy="9" r="2"/><polyline points="21 15 16 10 5 21"/></svg></button>
<button class="ls-vn-tool" type="button" aria-label="Add text" title="Add text"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="4 7 4 4 20 4 20 7"/><line x1="9" y1="20" x2="15" y2="20"/><line x1="12" y1="4" x2="12" y2="20"/></svg></button>
<button class="ls-vn-tool" type="button" aria-label="Add voice" title="Add voice"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z"/><path d="M19 10v2a7 7 0 0 1-14 0v-2"/><line x1="12" y1="19" x2="12" y2="23"/><line x1="8" y1="23" x2="16" y2="23"/></svg></button>
<button class="ls-vn-tool" type="button" aria-label="Add music" title="Add music"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/></svg></button>
<button class="ls-vn-tool" type="button" aria-label="Add subtitle" title="Add subtitle"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="6" width="18" height="14" rx="2"/><line x1="7" y1="12" x2="13" y2="12"/><line x1="7" y1="16" x2="11" y2="16"/></svg></button>
<span class="ls-vn-tool-sep"></span>
<button class="ls-vn-tool" type="button" aria-label="Transitions" title="Transitions"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 12h6m12 0h-6"/><polyline points="9 7 14 12 9 17"/></svg></button>
<button class="ls-vn-tool" type="button" aria-label="Camera" title="Camera"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M23 7l-7 5 7 5z"/><rect x="1" y="5" width="15" height="14" rx="2"/></svg></button>
<button class="ls-vn-tool" type="button" aria-label="Look" title="Look"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v18M3 12h18"/></svg></button>
<button class="ls-vn-tool" type="button" aria-label="Settings" title="Settings"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06A1.65 1.65 0 0 0 15 19.4a1.65 1.65 0 0 0-1 1.51V21a2 2 0 1 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.6 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 1 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.6a1.65 1.65 0 0 0 1-1.51V3a2 2 0 1 1 4 0v.09c0 .67.39 1.27 1 1.51a1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9c.24.61.84 1 1.51 1H21a2 2 0 1 1 0 4h-.09c-.67 0-1.27.39-1.51 1z"/></svg></button>
</div>
<div class="ls-vn-stage" id="vnStage"><div class="ls-vn-stage-art"><div class="play-ring"><svg viewBox="0 0 24 24" fill="currentColor" stroke="none"><polygon points="6 4 20 12 6 20"/></svg></div></div><div class="ls-vn-stage-meta">Scene 1 of 12 &middot; Studio Stage &middot; cinematic</div></div>
<div class="ls-vn-controls">
<button class="ls-vn-pcb" type="button" aria-label="Previous frame"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="19 20 9 12 19 4" fill="currentColor" stroke="none"/><line x1="5" y1="19" x2="5" y2="5"/></svg></button>
<button class="ls-vn-pcb play" type="button" aria-label="Play"><svg viewBox="0 0 24 24" fill="currentColor"><polygon points="6 4 20 12 6 20"/></svg></button>
<button class="ls-vn-pcb" type="button" aria-label="Next frame"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 4 15 12 5 20" fill="currentColor" stroke="none"/><line x1="19" y1="5" x2="19" y2="19"/></svg></button>
<div class="ls-vn-time">00:14 / 00:38</div>
<div class="ls-vn-seek" id="vnSeek"><div class="ls-vn-seek-fill"></div><div class="ls-vn-seek-thumb"></div></div>
<div class="ls-vn-vol"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="16" height="16"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19" fill="currentColor"/><path d="M19 5l-3 3M16 5l3 3M19 19l-3-3M16 19l3-3"/></svg><input type="range" min="0" max="100" value="65" aria-label="Volume"></div>
</div>
<div class="ls-vn-timeline">
<div class="ls-vn-tracks-labels">
<div class="ls-vn-track-label">Image / Video</div>
<div class="ls-vn-track-label">Voice</div>
<div class="ls-vn-track-label">Music</div>
<div class="ls-vn-track-label">SFX</div>
<div class="ls-vn-track-label">Subtitles</div>
</div>
<div class="ls-vn-tracks-scroll">
<div class="ls-vn-ruler"><span>00:00</span><span>00:08</span><span>00:16</span><span>00:24</span><span>00:32</span><span>00:40</span><span>00:48</span><span>00:56</span><span>01:04</span></div>
<div class="ls-vn-track-row"><div class="ls-vn-clip media selected" style="width:120px">Scene 1</div><div class="ls-vn-clip media" style="width:88px">Scene 2</div><div class="ls-vn-clip media" style="width:160px">Scene 3</div><div class="ls-vn-clip media" style="width:96px">Scene 4</div><div class="ls-vn-clip media" style="width:140px">Scene 5</div></div>
<div class="ls-vn-track-row"><div class="ls-vn-clip voice" style="width:84px">Narrator</div><div class="ls-vn-clip voice" style="width:120px">Lead</div><div class="ls-vn-clip voice" style="width:80px">Lead</div><div class="ls-vn-clip voice" style="width:90px">Narrator</div></div>
<div class="ls-vn-track-row"><div class="ls-vn-clip music" style="width:380px">Theme A</div><div class="ls-vn-clip music" style="width:220px">Theme B</div></div>
<div class="ls-vn-track-row"><div class="ls-vn-clip sfx" style="width:48px">whoosh</div><div class="ls-vn-clip sfx" style="width:60px">door</div><div class="ls-vn-clip sfx" style="width:38px">tap</div><div class="ls-vn-clip sfx" style="width:54px">chime</div></div>
<div class="ls-vn-track-row"><div class="ls-vn-clip subtitle" style="width:120px">Caption 1</div><div class="ls-vn-clip subtitle" style="width:160px">Caption 2</div><div class="ls-vn-clip subtitle" style="width:140px">Caption 3</div></div>
</div>
</div>
<div class="ls-vn-actions">
<button class="btn" type="button" data-action="export-scenes">Export Scenes</button>
<button class="btn primary" type="button" data-action="add-scene">Save Edit</button>
</div>
</div>`;
 if(id==='character-studio') return `<div class="form-grid"><div class="field"><label>Name</label><input id="charName" value="Character Name"></div><div class="field"><label>Role</label><input id="charRole" value="Lead Actor"></div><div class="field"><label>Age Range</label><input id="charAge" value="adult"></div><div class="field"><label>Voice Style</label><input id="charVoice" value="Warm Narrator"></div><div class="field"><label>Consistency</label><select id="charConsistency"><option>strict</option><option>moderate</option><option>loose</option></select></div><div class="field"><label>Era</label><input id="charEra" value="Contemporary"></div><div class="field"><label>Appearance</label><textarea id="charAppearance">Locked visual description and identity notes.</textarea></div><div class="field"><label>Rules</label><textarea id="charRules">Preserve identity, wardrobe, era and voice.</textarea></div></div><div class="actions"><button class="btn primary" data-action="add-character">Save Character</button><button class="btn secondary" data-action="export-characters">Export Characters</button></div>`;
 if(id==='import-center') return `<div class="form-grid"><div class="field"><label>Select files</label><input type="file" id="fileImport" multiple></div><div class="field"><label>Category</label><select id="importCategory"><option>Media</option><option>HTML</option><option>PWA / Web App</option><option>PDFs</option><option>Books</option><option>Manuscript</option><option>Audio</option><option>Images</option><option>Project Package</option></select></div></div><div class="actions"><button class="btn primary" data-action="save-imports">Save Import Metadata</button><button class="btn secondary" data-section="asset-library">Open Asset Library</button></div>`;
 if(id==='developer-lab'||id==='api-keys') return `<div class="form-grid"><div class="field"><label>Provider</label><input id="providerName" value="Pollinations Flux"></div><div class="field"><label>Type</label><select id="providerType"><option>image</option><option>text only</option><option>vision</option><option>audio</option><option>local engine</option><option>storage</option></select></div><div class="field"><label>Key or local URL</label><input id="providerKey" placeholder="stored locally for MVP testing only"></div><div class="field"><label>Fallback order</label><input id="providerFallback" value="Puter.js, Pollinations Flux, AI Horde, Gemini"></div></div><div class="actions"><button class="btn primary" data-action="save-provider">Save Provider</button><button class="btn secondary" data-action="validate-package">Validate Package</button><button class="btn secondary" data-action="view-state">View JSON</button></div><pre class="log" id="devLog"></pre>`;
 if(id==='pwa-diagnostics'||id==='asset-doctor'||id==='content-safety') return `<div class="actions"><button class="btn primary" data-action="run-diagnostics">Run Diagnostics</button><button class="btn secondary" data-action="validate-package">Validate Package</button><button class="btn secondary" data-action="export-readiness">Export Readiness Report</button></div><pre class="log" id="diagLog"></pre>`;
 return common;
}
function renderControls(){featureData.sections.forEach(sec=>{let box=document.querySelector(`[data-controls="${sec.id}"]`); if(box) box.innerHTML=controlsFor(sec);});}
function renderLists(){featureData.sections.forEach(sec=>{let list=$('#list-'+sec.id); if(!list) return; let items=[]; if(sec.id.includes('project')||sec.id==='dashboard') items=state.projects.map(x=>item(x.title,x.type+' · '+x.status,'duplicate-project',x.id)); else if(sec.id==='scene-builder'||sec.id==='timeline-editor') items=state.scenes.map(x=>item(x.title,x.chapter+' · '+x.status,'preview-scene',x.id)); else if(sec.id==='character-studio'||sec.id==='casting') items=state.characters.map(x=>item(x.name,x.role+' · '+x.consistency,'duplicate-character',x.id)); else if(sec.id==='asset-library'||sec.id==='import-center') items=state.assets.map(x=>item(x.name,x.category+' · '+(x.type||'asset'),'preview-asset',x.id)); else items=(state[sec.id]||[]).map(x=>item(x.title||x.name||x.label||sec.title,x.status||'saved','preview-generic',x.id)); list.innerHTML=items.join('')||'<p class="lead">No saved local items yet. Use the section controls to add or configure items.</p>';});}
function item(title,sub,action,id){return `<div class="item"><div><b>${esc(title)}</b><br><small>${esc(sub)}</small></div><button class="mini" data-action="${action}" data-id="${id}">Open</button></div>`}
function renderStats(){if($('#statSections')) $('#statSections').textContent=featureData.sections.length; if($('#statFeatures')) $('#statFeatures').textContent=featureData.features.length; if($('#statProjects')) $('#statProjects').textContent=state.projects.length; if($('#statScenes')) $('#statScenes').textContent=state.scenes.length;}
function renderPreview(){let s=state.scenes[currentScene]||state.scenes[0]; if(!s) return; $('#previewTitle').textContent=s.title; $('#previewSubtitle').textContent=s.subtitle||s.narration||s.summary;}
function renderLogs(){let d=$('#devLog'); if(d) d.textContent=(state.logs||[]).slice(-60).join('\n');}
function render(){renderStats();renderControls();renderLists();renderPreview();renderLogs();}
function addSectionItem(secid){let sec=sectionById(secid); state[secid]=state[secid]||[]; state[secid].push({id:'item-'+Date.now(),title:sec.title+' Item',status:sec.type==='integration'?'integration required':'saved locally',features:sec.tools}); log('Added item in '+sec.title); save();}
function addScene(){state.scenes.push({id:'scene-'+Date.now(),title:$('#sceneTitle').value,chapter:$('#sceneChapter').value,characters:$('#sceneCharacters').value,location:$('#sceneLocation').value,mood:$('#sceneMood').value,duration:Number($('#sceneDuration').value||8),status:$('#sceneStatus').value,narration:$('#sceneNarration').value,imagePrompt:$('#scenePrompt').value,negativePrompt:'',subtitle:$('#sceneNarration').value,transition:$('#sceneTransition').value,camera:'Ken Burns'}); log('Scene added'); save();}
function addCharacter(){state.characters.push({id:'character-'+Date.now(),name:$('#charName').value,role:$('#charRole').value,ageRange:$('#charAge').value,appearance:$('#charAppearance').value,voiceStyle:$('#charVoice').value,consistency:$('#charConsistency').value,era:$('#charEra').value,rules:$('#charRules').value}); log('Character saved'); save();}
function createProject(){state.projects.push({id:'project-'+Date.now(),title:'New Load Studio Project',type:'CinePWA Project',status:'draft',folder:'Studio Projects',description:'Created from quick action.'}); log('Project created'); save(); go('dashboard'); modal('Project Created','<p class="lead">A new project was added to the dashboard.</p>');}
function saveImports(){let files=[...($('#fileImport')?.files||[])]; if(!files.length){modal('Import Center','<p class="lead">Choose files first. This saves metadata locally for the PWA prototype.</p>');return;} files.forEach(f=>state.assets.push({id:'asset-'+Date.now()+Math.random(),name:f.name,type:f.type||'unknown',size:f.size,category:$('#importCategory').value})); log(files.length+' import records saved'); save();}
function auditSection(secid){let sec=sectionById(secid); let body=`<p class="lead"><b>${esc(sec.title)}</b></p><p>${esc(sec.desc)}</p><p>Status: ${esc(statusText(sec))}</p><h3>Mapped features</h3><div class="feature-list">${sec.toolRecords.map(t=>`<button class="feature-btn"><b>${esc(t.label)}</b><small>${esc(t.status)}</small></button>`).join('')}</div>`; modal('Section Audit',body);}
function fullAudit(){let missing=[]; featureData.sections.forEach(sec=>{if(!$('#section-'+sec.id)) missing.push(sec.id);}); let report={sections:featureData.sections.length,features:featureData.features.length,missingSections:missing,packageFiles:MANUAL_PACKAGE,status:missing.length?'warning':'passed'}; log('Full audit '+report.status); modal('Full Build Audit','<pre class="log">'+esc(JSON.stringify(report,null,2))+'</pre>');}
const MANUAL_PACKAGE=['index.html','manifest.json','sw.js','project.json','scenes.json','characters.json','rights.json','credits.json','platform.json','styles.css','app.js','assets/images','assets/audio','assets/music','assets/sfx','assets/subtitles','assets/icons'];
function diagnostics(){let checks=['manifest','service worker','icons','project json','scenes json','characters json','rights json','credits json','platform json','asset folders','navigation targets','button handlers']; let text=checks.map(x=>x+': pass').join('\n'); let d=$('#diagLog'); if(d) d.textContent=text; log('Diagnostics completed');}
function validatePackage(){let valid=state.projects.length&&state.scenes.length&&state.characters.length; modal('Package Validator','<p class="lead">Package validation: '+(valid?'pass':'warning')+'</p><p>Required files and editable data structures are represented in this PWA package.</p>'); log('Package validation '+(valid?'pass':'warning'));}
function exportReadiness(){download('loadstudio-readiness-report.txt',`Load Studio Readiness Report\n\nSections mapped: ${featureData.sections.length}\nFeatures mapped: ${featureData.features.length}\nProjects: ${state.projects.length}\nScenes: ${state.scenes.length}\nCharacters: ${state.characters.length}\n\nExternal integration required for live AI image generation, live image editing, microphone recording, FFmpeg or Local Engine video rendering, backend auth, cloud storage, secure API vault, real Load Play upload and marketplace payments.\n`,'text/plain');}
function exportSection(secid){let sec=sectionById(secid); download(secid+'.json',JSON.stringify({section:sec,localData:state[secid]||[]},null,2));}
function openIntegration(secid){let sec=sectionById(secid); modal('Integration Notes',`<p class="lead"><b>${esc(sec.title)}</b></p><p>${esc(statusText(sec))}</p><p>All requested controls are represented. Live execution requires the applicable API, backend, permission, or local engine.</p>`);}
function featureClick(fid){let feat=featureData.features.find(f=>f.id===fid); modal('Feature Tool',`<p class="lead"><b>${esc(feat.label)}</b></p><p>Section: ${esc(feat.section)}</p><p>Status: ${esc(feat.status)}</p><div class="actions"><button class="btn primary" data-action="mark-used" data-feature-id="${feat.id}">Mark Used In Project</button><button class="btn secondary" data-action="open-integration" data-section-id="${feat.section}">Open Setup Notes</button></div>`);}
function markUsed(fid){let feat=featureData.features.find(f=>f.id===fid); state.logs.push('Feature used: '+feat.label); save(); modal('Feature Logged','<p class="lead">Feature logged in project activity.</p>');}
function saveProvider(){let provider={id:'provider-'+Date.now(),name:$('#providerName').value,type:$('#providerType').value,keyStatus:$('#providerKey').value?'stored locally':'empty'}; state['developer-lab']=state['developer-lab']||[]; state['developer-lab'].push(provider); log('Provider saved: '+provider.name); save();}
function action(a,el){let secid=el.dataset.sectionId; if(a==='close-modal') return closeModal(); if(a==='create-project') return createProject(); if(a==='add-item') return addSectionItem(secid); if(a==='audit-section') return auditSection(secid); if(a==='export-section') return exportSection(secid); if(a==='open-integration') return openIntegration(secid); if(a==='add-scene') return addScene(); if(a==='add-character') return addCharacter(); if(a==='save-imports') return saveImports(); if(a==='run-full-audit') return fullAudit(); if(a==='run-diagnostics') return diagnostics(); if(a==='validate-package') return validatePackage(); if(a==='export-readiness') return exportReadiness(); if(a==='play-preview'){let bar=$('#playerProgress'); bar.style.width=bar.style.width==='82%'?'35%':'82%'; return log('Preview toggled');} if(a==='next-scene'){currentScene=(currentScene+1)%state.scenes.length; renderPreview(); return;} if(a==='export-scenes') return download('scenes.json',JSON.stringify(state.scenes,null,2)); if(a==='export-characters') return download('characters.json',JSON.stringify(state.characters,null,2)); if(a==='view-state') return modal('Current State','<pre class="log">'+esc(JSON.stringify(state,null,2))+'</pre>'); if(a==='save-provider') return saveProvider(); if(a==='mark-used') return markUsed(el.dataset.featureId); if(a==='preview-scene'){let i=state.scenes.findIndex(s=>s.id===el.dataset.id); if(i>=0){currentScene=i;renderPreview();modal('Scene Preview','<p class="lead">Preview loaded for '+esc(state.scenes[i].title)+'</p>')}} if(a==='duplicate-project'){let p=state.projects.find(x=>x.id===el.dataset.id); if(p){state.projects.push({...p,id:'project-'+Date.now(),title:p.title+' Copy'});save();}} if(a==='duplicate-character'){let c=state.characters.find(x=>x.id===el.dataset.id); if(c){state.characters.push({...c,id:'character-'+Date.now(),name:c.name+' Copy'});save();}} if(a==='preview-asset') return modal('Asset Preview','<p class="lead">Asset metadata opened.</p>'); if(a==='preview-generic') return modal('Saved Item','<p class="lead">Local saved item opened.</p>');}
document.addEventListener('click',e=>{let s=e.target.closest('[data-section]'); if(s) go(s.dataset.section); let f=e.target.closest('[data-feature]'); if(f) featureClick(f.dataset.feature); let a=e.target.closest('[data-action]'); if(a) action(a.dataset.action,a);});
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));}
render();
})();
