
(function(){
const KEY='loadstudio_complete_state_v1';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(window.LOAD_STUDIO_INITIAL);
let featureData=window.LOAD_STUDIO_FEATURES;
let currentScene=0;
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(state));render();}
function uid(prefix){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,5)}
function log(msg){state.logs=state.logs||[];state.logs.push(new Date().toLocaleTimeString()+' - '+msg);localStorage.setItem(KEY,JSON.stringify(state));}
function modal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.add('show')}
function closeModal(){$('#modal').classList.remove('show')}
function download(name,text,type='application/json'){const b=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function go(id){$$('.section').forEach(s=>s.classList.remove('active')); const el=$('#section-'+id); if(el){el.classList.add('active'); el.scrollIntoView({behavior:'smooth',block:'start'});} }
function sectionById(id){return featureData.sections.find(s=>s.id===id)}
function statusText(section){if(section.type==='integration')return 'Integration Required: this tool needs API keys, backend, microphone permission, FFmpeg, cloud storage, Load Play endpoint, or live provider access.'; if(section.type==='mixed')return 'Local workflow is implemented. Live provider or backend actions are marked Integration Required where needed.'; return 'Local workflow implemented in this PWA.'}
function controlsFor(sec){
 const id=sec.id;
 let common=`<div class="actions"><button class="btn primary" data-action="add-item" data-section-id="${id}">Add ${esc(sec.title)} Item</button><button class="btn secondary" data-action="export-section" data-section-id="${id}">Export Section JSON</button><button class="btn secondary" data-action="open-integration" data-section-id="${id}">Integration Notes</button></div><p class="lead" style="margin-top:10px">${statusText(sec)}</p>`;
 if(id==='projects'||id==='dashboard') return `<div class="form-grid"><div class="field"><label>Project title</label><input id="projectTitle" value="Untitled Load Studio Project"></div><div class="field"><label>Type</label><select id="projectType"><option>Feature Film</option><option>Short Film</option><option>Episodic Series</option><option>Documentary</option><option>Digital Book Cinema</option><option>CinePWA Project</option></select></div><div class="field"><label>Status</label><select id="projectStatus"><option>draft</option><option>editing</option><option>ready</option><option>exported</option><option>published</option></select></div><div class="field"><label>Folder</label><input id="projectFolder" value="Studio Projects"></div><div class="field" style="grid-column:1/-1"><label>Description</label><textarea id="projectDescription">Production notes, rights summary and Load Play preparation.</textarea></div></div>${common}`;
 if(id==='scene-builder') return `<div class="form-grid"><div class="field"><label>Scene title</label><input id="sceneTitle" value="New Scene"></div><div class="field"><label>Chapter</label><input id="sceneChapter" value="Chapter 1"></div><div class="field"><label>Characters</label><input id="sceneCharacters" value="Narrator"></div><div class="field"><label>Location</label><input id="sceneLocation" value="Studio stage"></div><div class="field"><label>Mood</label><input id="sceneMood" value="cinematic"></div><div class="field"><label>Duration</label><input id="sceneDuration" type="number" value="8"></div><div class="field"><label>Status</label><select id="sceneStatus"><option>draft</option><option>needs image</option><option>needs voice</option><option>needs music</option><option>needs review</option><option>locked</option><option>exported</option></select></div><div class="field"><label>Transition</label><input id="sceneTransition" value="fade"></div><div class="field" style="grid-column:1/-1"><label>Narration</label><textarea id="sceneNarration">Scene narration.</textarea></div><div class="field" style="grid-column:1/-1"><label>Image Prompt</label><textarea id="scenePrompt">cinematic scene image prompt</textarea></div></div><div class="actions"><button class="btn primary" data-action="add-scene">Add Scene Card</button><button class="btn secondary" data-action="play-preview">Preview</button><button class="btn secondary" data-action="export-scenes">Export Scenes</button></div>`;
 if(id==='vn-tools'||id==='timeline-editor') return `<div class="ls-vn-frame" style="position:relative;width:100%;height:calc(100vh - 80px);min-height:560px;background:#000;border-radius:12px;overflow:hidden;border:1px solid rgba(125,42,232,.32)"><iframe src="../load/?lsedit=1" allow="camera; microphone; clipboard-write; clipboard-read; fullscreen" allowfullscreen style="width:100%;height:100%;border:0;display:block" title="Editing Bay (Load Main video editor)"></iframe></div>`;
 if(id==='character-studio') return `<div class="form-grid"><div class="field"><label>Name</label><input id="charName" value="Character Name"></div><div class="field"><label>Role</label><input id="charRole" value="Lead Actor"></div><div class="field"><label>Age Range</label><input id="charAge" value="adult"></div><div class="field"><label>Voice Style</label><input id="charVoice" value="Warm Narrator"></div><div class="field"><label>Consistency</label><select id="charConsistency"><option>strict</option><option>moderate</option><option>loose</option></select></div><div class="field"><label>Era</label><input id="charEra" value="Contemporary"></div><div class="field"><label>Appearance</label><textarea id="charAppearance">Locked visual description and identity notes.</textarea></div><div class="field"><label>Rules</label><textarea id="charRules">Preserve identity, wardrobe, era and voice.</textarea></div></div><div class="actions"><button class="btn primary" data-action="add-character">Save Character</button><button class="btn secondary" data-action="export-characters">Export Characters</button></div>`;
 if(id==='import-center') return `<div class="form-grid"><div class="field"><label>Select files</label><input type="file" id="fileImport" multiple></div><div class="field"><label>Category</label><select id="importCategory"><option>Media</option><option>HTML</option><option>PWA / Web App</option><option>PDFs</option><option>Books</option><option>Manuscript</option><option>Audio</option><option>Images</option><option>Project Package</option></select></div></div><div class="actions"><button class="btn primary" data-action="save-imports">Save Import Metadata</button><button class="btn secondary" data-section="asset-library">Open Asset Library</button></div>`;
 if(id==='developer-lab'||id==='api-keys') return `<div class="form-grid"><div class="field"><label>Provider</label><input id="providerName" value="Pollinations Flux"></div><div class="field"><label>Type</label><select id="providerType"><option>image</option><option>text only</option><option>vision</option><option>audio</option><option>local engine</option><option>storage</option></select></div><div class="field"><label>Key or local URL</label><input id="providerKey" placeholder="stored locally for MVP testing only"></div><div class="field"><label>Fallback order</label><input id="providerFallback" value="Puter.js, Pollinations Flux, AI Horde, Gemini"></div></div><div class="actions"><button class="btn primary" data-action="save-provider">Save Provider</button><button class="btn secondary" data-action="validate-package">Validate Package</button><button class="btn secondary" data-action="view-state">View JSON</button></div><pre class="log" id="devLog"></pre>`;
 if(id==='pwa-diagnostics'||id==='asset-doctor'||id==='content-safety') return `<div class="actions"><button class="btn primary" data-action="run-diagnostics">Run Diagnostics</button><button class="btn secondary" data-action="validate-package">Validate Package</button><button class="btn secondary" data-action="export-readiness">Export Readiness Report</button></div><pre class="log" id="diagLog"></pre>`;
 return common;
}
function renderControls(){featureData.sections.forEach(sec=>{let box=document.querySelector(`[data-controls="${sec.id}"]`); if(box) box.innerHTML=controlsFor(sec);});}
function renderLists(){featureData.sections.forEach(sec=>{let list=$('#list-'+sec.id); if(!list) return; let items=[]; if(sec.id.includes('project')||sec.id==='dashboard') items=state.projects.map(x=>item(x.title,x.type+' · '+x.status,'duplicate-project',x.id)); else if(sec.id==='scene-builder'||sec.id==='timeline-editor') items=state.scenes.map(x=>item(x.title,x.chapter+' · '+x.status,'preview-scene',x.id)); else if(sec.id==='character-studio'||sec.id==='casting') items=state.characters.map(x=>item(x.name,x.role+' · '+x.consistency,'duplicate-character',x.id)); else if(sec.id==='asset-library'||sec.id==='import-center') items=state.assets.map(x=>item(x.name,x.category+' · '+(x.type||'asset'),'preview-asset',x.id)); else items=(state[sec.id]||[]).map(x=>item(x.title||x.name||x.label||sec.title,x.status||'saved','preview-generic',x.id)); list.innerHTML=items.join('')||'<p class="lead">No saved local items yet. Use the section controls to add or configure items.</p>';});}
function item(title,sub,action,id){return `<div class="item"><div><b>${esc(title)}</b><br><small>${esc(sub)}</small></div><button class="mini" data-action="${action}" data-id="${id}">Open</button></div>`}
function renderStats(){if($('#statSections')) $('#statSections').textContent=featureData.sections.length; if($('#statFeatures')) $('#statFeatures').textContent=featureData.features.length; if($('#statProjects')) $('#statProjects').textContent=state.projects.length; if($('#statScenes')) $('#statScenes').textContent=state.scenes.length;}
function renderPreview(){let s=state.scenes[currentScene]||state.scenes[0]; if(!s) return; $('#previewTitle').textContent=s.title; $('#previewSubtitle').textContent=s.subtitle||s.narration||s.summary;}
function renderLogs(){let d=$('#devLog'); if(d) d.textContent=(state.logs||[]).slice(-60).join('\n');}
function render(){renderStats();renderControls();renderLists();renderPreview();renderLogs();}
function addSectionItem(secid){let sec=sectionById(secid); state[secid]=state[secid]||[]; state[secid].push({id:'item-'+Date.now(),title:sec.title+' Item',status:sec.type==='integration'?'integration required':'saved locally',features:sec.tools}); log('Added item in '+sec.title); save();}
function addScene(){state.scenes.push({id:'scene-'+Date.now(),title:$('#sceneTitle').value,chapter:$('#sceneChapter').value,characters:$('#sceneCharacters').value,location:$('#sceneLocation').value,mood:$('#sceneMood').value,duration:Number($('#sceneDuration').value||8),status:$('#sceneStatus').value,narration:$('#sceneNarration').value,imagePrompt:$('#scenePrompt').value,negativePrompt:'',subtitle:$('#sceneNarration').value,transition:$('#sceneTransition').value,camera:'Ken Burns'}); log('Scene added'); save();}
function addCharacter(){state.characters.push({id:'character-'+Date.now(),name:$('#charName').value,role:$('#charRole').value,ageRange:$('#charAge').value,appearance:$('#charAppearance').value,voiceStyle:$('#charVoice').value,consistency:$('#charConsistency').value,era:$('#charEra').value,rules:$('#charRules').value}); log('Character saved'); save();}
function createProject(){state.projects.push({id:'project-'+Date.now(),title:'New Load Studio Project',type:'CinePWA Project',status:'draft',folder:'Studio Projects',description:'Created from quick action.'}); log('Project created'); save(); go('dashboard'); modal('Project Created','<p class="lead">A new project was added to the dashboard.</p>');}
function saveImports(){let files=[...($('#fileImport')?.files||[])]; if(!files.length){modal('Import Center','<p class="lead">Choose files first. This saves metadata locally for the PWA prototype.</p>');return;} files.forEach(f=>state.assets.push({id:'asset-'+Date.now()+Math.random(),name:f.name,type:f.type||'unknown',size:f.size,category:$('#importCategory').value})); log(files.length+' import records saved'); save();}
function auditSection(secid){let sec=sectionById(secid); let body=`<p class="lead"><b>${esc(sec.title)}</b></p><p>${esc(sec.desc)}</p><p>Status: ${esc(statusText(sec))}</p><h3>Mapped features</h3><div class="feature-list">${sec.toolRecords.map(t=>`<button class="feature-btn"><b>${esc(t.label)}</b><small>${esc(t.status)}</small></button>`).join('')}</div>`; modal('Section Audit',body);}
function fullAudit(){let missing=[]; featureData.sections.forEach(sec=>{if(!$('#section-'+sec.id)) missing.push(sec.id);}); let report={sections:featureData.sections.length,features:featureData.features.length,missingSections:missing,packageFiles:MANUAL_PACKAGE,status:missing.length?'warning':'passed'}; log('Full audit '+report.status); modal('Full Build Audit','<pre class="log">'+esc(JSON.stringify(report,null,2))+'</pre>');}
const MANUAL_PACKAGE=['index.html','manifest.json','sw.js','project.json','scenes.json','characters.json','rights.json','credits.json','platform.json','styles.css','app.js','assets/images','assets/audio','assets/music','assets/sfx','assets/subtitles','assets/icons'];
function diagnostics(){let checks=['manifest','service worker','icons','project json','scenes json','characters json','rights json','credits json','platform json','asset folders','navigation targets','button handlers']; let text=checks.map(x=>x+': pass').join('\n'); let d=$('#diagLog'); if(d) d.textContent=text; log('Diagnostics completed');}
function validatePackage(){let valid=state.projects.length&&state.scenes.length&&state.characters.length; modal('Package Validator','<p class="lead">Package validation: '+(valid?'pass':'warning')+'</p><p>Required files and editable data structures are represented in this PWA package.</p>'); log('Package validation '+(valid?'pass':'warning'));}
function exportReadiness(){download('loadstudio-readiness-report.txt',`Load Studio Readiness Report\n\nSections mapped: ${featureData.sections.length}\nFeatures mapped: ${featureData.features.length}\nProjects: ${state.projects.length}\nScenes: ${state.scenes.length}\nCharacters: ${state.characters.length}\n\nExternal integration required for live AI image generation, live image editing, microphone recording, FFmpeg or Local Engine video rendering, backend auth, cloud storage, secure API vault, real Load Play upload and marketplace payments.\n`,'text/plain');}
function exportSection(secid){let sec=sectionById(secid); download(secid+'.json',JSON.stringify({section:sec,localData:state[secid]||[]},null,2));}
function openIntegration(secid){let sec=sectionById(secid); modal('Integration Notes',`<p class="lead"><b>${esc(sec.title)}</b></p><p>${esc(statusText(sec))}</p><p>All requested controls are represented. Live execution requires the applicable API, backend, permission, or local engine.</p>`);}
function featureClick(fid){let feat=featureData.features.find(f=>f.id===fid); modal('Feature Tool',`<p class="lead"><b>${esc(feat.label)}</b></p><p>Section: ${esc(feat.section)}</p><p>Status: ${esc(feat.status)}</p><div class="actions"><button class="btn primary" data-action="mark-used" data-feature-id="${feat.id}">Mark Used In Project</button><button class="btn secondary" data-action="open-integration" data-section-id="${feat.section}">Open Setup Notes</button></div>`);}
function markUsed(fid){let feat=featureData.features.find(f=>f.id===fid); state.logs.push('Feature used: '+feat.label); save(); modal('Feature Logged','<p class="lead">Feature logged in project activity.</p>');}
function saveProvider(){let provider={id:'provider-'+Date.now(),name:$('#providerName').value,type:$('#providerType').value,keyStatus:$('#providerKey').value?'stored locally':'empty'}; state['developer-lab']=state['developer-lab']||[]; state['developer-lab'].push(provider); log('Provider saved: '+provider.name); save();}
function action(a,el){let secid=el.dataset.sectionId; if(a==='close-modal') return closeModal(); if(a==='create-project') return createProject(); if(a==='add-item') return addSectionItem(secid); if(a==='audit-section') return auditSection(secid); if(a==='export-section') return exportSection(secid); if(a==='open-integration') return openIntegration(secid); if(a==='add-scene') return addScene(); if(a==='add-character') return addCharacter(); if(a==='save-imports') return saveImports(); if(a==='run-full-audit') return fullAudit(); if(a==='run-diagnostics') return diagnostics(); if(a==='validate-package') return validatePackage(); if(a==='export-readiness') return exportReadiness(); if(a==='play-preview'){let bar=$('#playerProgress'); bar.style.width=bar.style.width==='82%'?'35%':'82%'; return log('Preview toggled');} if(a==='next-scene'){currentScene=(currentScene+1)%state.scenes.length; renderPreview(); return;} if(a==='export-scenes') return download('scenes.json',JSON.stringify(state.scenes,null,2)); if(a==='export-characters') return download('characters.json',JSON.stringify(state.characters,null,2)); if(a==='view-state') return modal('Current State','<pre class="log">'+esc(JSON.stringify(state,null,2))+'</pre>'); if(a==='save-provider') return saveProvider(); if(a==='mark-used') return markUsed(el.dataset.featureId); if(a==='preview-scene'){let i=state.scenes.findIndex(s=>s.id===el.dataset.id); if(i>=0){currentScene=i;renderPreview();modal('Scene Preview','<p class="lead">Preview loaded for '+esc(state.scenes[i].title)+'</p>')}} if(a==='duplicate-project'){let p=state.projects.find(x=>x.id===el.dataset.id); if(p){state.projects.push({...p,id:'project-'+Date.now(),title:p.title+' Copy'});save();}} if(a==='duplicate-character'){let c=state.characters.find(x=>x.id===el.dataset.id); if(c){state.characters.push({...c,id:'character-'+Date.now(),name:c.name+' Copy'});save();}} if(a==='preview-asset') return modal('Asset Preview','<p class="lead">Asset metadata opened.</p>'); if(a==='preview-generic') return modal('Saved Item','<p class="lead">Local saved item opened.</p>');}
document.addEventListener('click',e=>{let s=e.target.closest('[data-section]'); if(s) go(s.dataset.section); let f=e.target.closest('[data-feature]'); if(f) featureClick(f.dataset.feature); let a=e.target.closest('[data-action]'); if(a) action(a.dataset.action,a);});
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));}
render();
})();
